### ISSUE TITLE
TypeError in tests: Cannot read property 'ACTIVE' of undefined

### ISSUE THREAD

**Issue by TrebuhD** [ajsmth/react-native-pager#26]
I'm getting a `TypeError` when rendering a component which uses this package with `react-test-renderer`:

```
    TypeError: Cannot read property 'ACTIVE' of undefined

      at ACTIVE (node_modules/@crowdlinker/react-native-pager/src/pager.tsx:301:32)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6156:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8690:13)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10058:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14708:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14681:22)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14380:11)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2063:24
      at unstable_runWithPriority (node_modules/react-test-renderer/node_modules/scheduler/cjs/scheduler.development.js:697:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2013:10)
```

It comes down to the `State` object imported from `react-native-gesture-handler`, which I see is mocked in the jest setup file of this library. I also have it mocked, but no matter what I do (delete the mock, etc), my tests crash with the above error.

**Comment by ajsmth** [comment]
hey there - are you using your own mock or the one exported by this library? in either case, i believe the reanimated package has updated their mock and it broke some functionality, but i don't see how that would affect the gesture handler library. 

could it be a caching issue? i've had to clear my jest cache in the past to fix these kinds of issues

**Comment by TrebuhD** [comment]
Hi @ajsmth . I have my own mock, but if I delete it, I get another (similar) error:
```
 FAIL  src/onboarding/OnboardingScreenContainer.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'Direction' of undefined

      at Object.Direction (node_modules/react-native-gesture-handler/Directions.js:3:39)
      at Object.<anonymous> (node_modules/react-native-gesture-handler/GestureHandler.js:2:1)
```

I tried clearing my cache, to no avail. 

The problem seems to be on [line 301 in `pager.tsx`,](https://github.com/CrowdLinker/react-native-pager/blob/master/src/pager.tsx#L301), where the `State` object is `undefined`. Which is strange, since it's there both in your mock and mine.

Here's my mock:
```typescript
export default {
  ScrollView,
  PanGestureHandler: View,
  attachGestureHandler: () => {},
  createGestureHandler: () => {},
  dropGestureHandler: () => {},
  updateGestureHandler: () => {},
  Direction: {
    RIGHT: 1,
    LEFT: 2,
    UP: 4,
    DOWN: 8,
  },
  State: {
    BEGAN: "BEGAN",
    FAILED: "FAILED",
    ACTIVE: "ACTIVE",
    END: "END",
    UNDETERMINED: "UNDETERMINED",
  },
  Swipeable: View,
  DrawerLayout: View,
  Slider: View,
  Switch: View,
  TextInput: View,
  ToolbarAndroid: View,
  ViewPagerAndroid: View,
  DrawerLayoutAndroid: View,
  WebView: View,
  NativeViewGestureHandler: View,
  TapGestureHandler: View,
  FlingGestureHandler: View,
  ForceTouchGestureHandler: View,
  LongPressGestureHandler: View,
  PinchGestureHandler: View,
  RotationGestureHandler: View,
  /* Buttons */
  RawButton: View,
  BaseButton: View,
  RectButton: View,
  BorderlessButton: View,
  /* Other */
  FlatList: View,
  gestureHandlerRootHOC: jest.fn(),
  Directions: {},
};
```

**Comment by ajsmth** [comment]
odd. especially considering 'Direction' isn't used anywhere that i can recall. i suspect thats used in your client code somewhere? 

the mock i've been using most recently is this:
```
jest.mock('react-native-gesture-handler', () => {
  const View = require('react-native/Libraries/Components/View/View');
  const TouchableOpacity = require('react-native/Libraries/Components/Touchable/TouchableOpacity');
  const Flatlist = require('react-native/Libraries/Lists/FlatList');
  return {
    Swipeable: View,
    DrawerLayout: View,
    State: {},
    ScrollView: View,
    Slider: View,
    Switch: View,
    TextInput: View,
    ToolbarAndroid: View,
    ViewPagerAndroid: View,
    DrawerLayoutAndroid: View,
    WebView: View,
    NativeViewGestureHandler: View,
    TapGestureHandler: View,
    FlingGestureHandler: View,
    ForceTouchGestureHandler: View,
    LongPressGestureHandler: View,
    PanGestureHandler: View,
    PinchGestureHandler: View,
    RotationGestureHandler: View,
    /* Buttons */
    RawButton: View,
    BaseButton: View,
    RectButton: View,
    BorderlessButton: View,
    TouchableOpacity: TouchableOpacity,
    /* Other */
    FlatList: Flatlist,
    gestureHandlerRootHOC: jest.fn(),
    Directions: {},
  };
});
```

not sure if that is of any use to you

**Comment by ajsmth** [comment]
@TrebuhD any luck with this?

**Comment by TrebuhD** [comment]
@ajsmth the bug was in my client code indeed. I can't remember what it was now but if you think it's important, I can take a look.

Thanks a lot for all the help! I think we can close this.

**Comment by ajsmth** [comment]
okay great - i was just curious. thanks! i'll close
